language: elixir
elixir:
  - 1.4.1
addons:
  postgresql: '9.4'
env:
  - MIX_ENV=test
before_script:
  - mix do ecto.create, ecto.migrate
script:
  - mix do deps.get, test && mix compile && mix coveralls.travis
notifications:
  email: false
after_success:
  - bash <(curl -s https://codecov.io/bash)
