language: elixir
elixir:
  - 1.4.1

script:
  - MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
